version: 0.1
phases:
  build:
    command:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Harsh_CoverLetterM.docx
    - styles/main.css
    - images/*
    - dist/bundle.js
